"""Added password to user model

Revision ID: 2b1858cdb486
Revises: 18aa52bdc6
Create Date: 2014-09-20 19:06:57.547590

"""

# revision identifiers, used by Alembic.
revision = '2b1858cdb486'
down_revision = '18aa52bdc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
